###################
# ENV VARS:
# # - FULL_NAME
# # - EMAIL
# - PAT (generated at Personal Access Tokens - with workflow access checked)
###################

name: Check for new releases
# Automatically check for new releases (new versions)
on:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Fetch release version
        id: fetch-version
       # run: |
       #   curl -sL https://raw.githubusercontent.com/n8n-io/n8n/master/package.json | jq -r ".version" > release-versions/n8n-latest.txt
       #   echo ::set-output name=version::$(cat release-versions/n8n-latest.txt)
       run: |
          # 使用 GitHub API 獲取最新的穩定發行版，並從回應的 JSON 中提取 tag_name
          # 增加了 Authorization header 以避免 API 頻率限制
          curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/n8n-io/n8n/releases/latest \
            | jq -r ".tag_name" > release-versions/n8n-latest.txt
          
          # 將版本號設定為後續步驟可用的輸出變數 (使用新的 GITHUB_OUTPUT 語法)
          echo "version=$(cat release-versions/n8n-latest.txt)" >> $GITHUB_OUTPUT

      #      - name: Check for modified files
      #        id: git-check
      #        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      #      - name: Commit latest release version
      #        if: steps.git-check.outputs.modified == 'true'
      #        run: |
      #          git config --global user.name '${{ secrets.FULL_NAME }}'
      #          git config --global user.email '${{ secrets.EMAIL }}'
      #          git commit -am "New release: $(cat release-versions/n8n-latest.txt)"
      #          git push

      #- uses: stefanzweifel/git-auto-commit-action@v5
      #  with:
      #    commit_message: New auto release v${{steps.fetch-version.outputs.version}}
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): New n8n version v${{ steps.fetch-version.outputs.version }}"
          # 可選：指定要提交的檔案，更精確
          file_pattern: release-versions/n8n-latest.txt 
